---
- name: Import tasks if distribution family.
  import_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Copy configuration template.
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    group: root
    owner: root
    mode: 0644
    backup: yes
  notify: restart filebeat
