---
- hosts: [localhost,all]
  become: yes
  roles: 
    - cloudalchemy.node-exporter
  vars:
    node_exporter_version: latest
    node_exporter_web_listen_address: '{{ hostvars[inventory_hostname]["ansible_host"] }}:9100'
    subnet: "192.168.213.0/24"
    master_node_addr: "192.168.213.10"
  tasks:
    - name: Open port 9100/tcp.
      firewalld:
        zone: FedoraServer
        rich_rule: "rule family=ipv4 source address='{{ subnet }}' port port=9100 protocol=tcp accept"
        permanent: yes
        immediate: yes
        state: enabled

- hosts: localhost
  become: yes
  roles:
    - cloudalchemy.prometheus
  vars:
    prometheus_web_listen_address: "{{ master_node_addr }}:9089"
    prometheus_scrape_configs:
      - job_name: "prometheus-server"
        metrics_path: "/metrics"
        static_configs:
          - targets:
            - "{{ master_node_addr }}:9089"
      - job_name: "prometheus-nodes"
        dns_sd_configs:
          - names: 
            - "_prometheus._tcp.talos.net"
  tasks:
    - name: Open port 9089/tcp.
      firewalld:
        zone: FedoraServer
        rich_rule: "rule family=ipv4 source address='{{ subnet }}' port port=9089 protocol=tcp accept"
        permanent: yes
        immediate: yes
        state: enabled
