---
- hosts: [localhost, fs11]
  become: yes

  tasks:
    - name: Install packages for High Availability.
      dnf:
        name: ["pcs", "pacemaker", "fence-agents-all"]
        state: latest

    - name: Set password hacluster user.
      user:
        name: hacluster
        password: "{ vault_hacluster_password }"

    - name: Open the necessary ports for High Availability.
      firewalld:
        zone: FedoraServer
        rich_rule: "rule family=ipv4 source address=10.0.8.0/24 service name='high-availability' accept"
        permanent: yes
        immediate: yes
        state: enabled

    - name: Start pcsd service.
      systemd:
        name: pcsd
        state: started

