---
- hosts: all
  become: yes
  tasks:
    - name: Install GlusterFS.
      dnf:
        name: glusterfs-server
        state: latest
    
    - name: Start the GlusterFS management daemon.
      systemd:
        name: glusterd
        enabled: yes
        state: restarted

    - name: Allow traffic for GlusterFS service.
      firewalld:
        zone: FedoraServer
        rich_rule: "rule family=ipv4 source address=10.0.8.0/24 service name='glusterfs' accept"
        immediate: yes
        permanent: yes
        state: enabled

    - name: Create directory for gluster volume 1.
      file:
        state: directory
        recurse: yes
        path: /data/brick1/gv1

# gluster volume create gv1 replica 3 server1:/data/brick1/gv1 server2:/data/brick1/gv1 server3:/data/brick1/gv1
# gluster volume create gv1 replica 3 fs11.talos.net:/data/brick1/gv1 fs12.talos.net:/data/brick1/gv1 fs13.talos.net:/data/brick1/gv1
# volume create: gv1: success: please start the volume to access data
# gluster volume start gv1
# volume start: gv1: success
