# TCP port 2377 for cluster management communications
# TCP and UDP port 7946 for communication among nodes
# UDP port 4789 for overlay network traffic
---
- hosts: ["localhost", "all"]
  become: yes
      
  tasks:
    - name: Open TCP ports between the swarm nodes.
      firewalld:
        rich_rule: "rule family=ipv4 source address=10.0.8.0/24 port port={{ item }} protocol=tcp accept"
        zone: FedoraServer
        permanent: yes
        immediate: yes
        state: enabled
      loop: ["2377", "7946"]

    - name: Open UDP ports between the swarm nodes.
      firewalld:
        rich_rule: "rule family=ipv4 source address=10.0.8.0/24 port port={{ item }} protocol=udp accept"
        zone: FedoraServer
        permanent: yes
        immediate: yes
        state: enabled
      loop: ["4789", "7946"]
