---
- name: Open TCP ports between the swarm nodes.
  firewalld:
    rich_rule: "rule family=ipv4 source address={{ docker_cluster_management_ip_subnet }} port port={{ item }} protocol=tcp accept"
    zone: "{{ docker_cluster_management_firewall_zone }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: '{{ docker_swarm_ports["tcp"] }}'

- name: Open UDP ports between the swarm nodes.
  firewalld:
    rich_rule: "rule family=ipv4 source address={{ docker_cluster_management_ip_subnet }} port port={{ item }} protocol=udp accept"
    zone: "{{ docker_cluster_management_firewall_zone }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: '{{ docker_swarm_ports["udp"] }}'
