# https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts
# TCP port 2377 for cluster management communications
# TCP and UDP port 7946 for communication among nodes
# UDP port 4789 for overlay network traffic
# TCP port 9323 for docker metrics
---
- name: Open the necessary firewall ports for Docker Swarm.
  ansible.posix.firewalld:
    zone: "{{ docker_swarm_management_firewall_zone }}"
    state: enabled
    permanent: yes
    immediate: yes
    rich_rule: rule family=ipv4 source address="{{ docker_swarm_management_ip_subnet }}" port port="{{ item.port }}" protocol="{{ item.protocol }}" accept
  loop:
    - { port: 2377, protocol: "tcp" }
    - { port: 7946, protocol: "tcp" }
    - { port: 7946, protocol: "udp" }
    - { port: 4789, protocol: "udp" }
    - { port: 9323, protocol: "tcp" }

- name: Open port 9323/tcp for docker metrics.
  ansible.posix.firewalld:
    port: 9323/tcp
    permanent: yes
    state: enabled
    immediate: yes
