---
- name: Copy docker config file.
  copy:
    src: templates/daemon.json
    dest: "{{ docker_conf_path }}"
    owner: root
    group: root
    mode: "0644"
- name: Check if file was successfully created.
  stat:
    path: "{{ docker_conf_path }}"
  register: st
- name: Fail if no file exists in path.
  fail:
    msg: "File not found in path: {{ docker_conf_path }}."
  when: st.stat.exists == False
- name: Replace line in file with host address.
  lineinfile:
    path: "{{ docker_conf_path }}"
    regexp: ".\"metrics-addr.*"
    line: "    \"metrics-addr\": \"{{ ansible_host }}:{{ docker['metrics_port'] }}\","
    owner: root
    group: root
    mode: "0644"