---
- name: Check if docker swarm master address is reachable.
  wait_for:
    host: "{{ docker_swarm['master_node_addr'] }}"
    port: 2377
    timeout: 10
    state: started

- name: Remove old Docker versions.
  dnf:
    state: absent
    name: 
      - "docker-client"
      - "docker-client-latest"
      - "docker-common"
      - "docker-latest"
      - "docker-latest-logrotate"
      - "docker-logrotate"
      - "docker-selinux"
      - "docker-engine-selinux"
      - "docker-engine"

- name: Install python dependencies with pip.
  pip:
    state: present
    name: ["docker"]
