---
- name: Join Docker Swarm cluster.
  community.general.docker_swarm:
    state: join
    advertise_addr: "{{ ansible_host }}"
    join_token: "{{ vault_docker_swarm_token }}"
    remote_addrs: ["{{ docker_swarm['master_node_addr'] }}:2377"]
  when:
    - ansible_connection != "local"