---
# TCP port 2377 for cluster management communications
# TCP and UDP port 7946 for communication among nodes
# UDP port 4789 for overlay network traffic

docker_cluster_management_ip_subnet: "10.0.8.0/24"
docker_cluster_management_firewall_zone: "FedoraServer"
docker_swarm_master_node: "10.0.8.11"
docker_swarm_ports:
  udp: ["2377", "7946"]
  tcp: ["4789", "7946"]
