---
- import_tasks: repo.yml

- name: Install the latest version of the kubernetes control plane applications.
  dnf:
    name: ["kubectl", "kubeadm"]
    state: present
    update_cache: yes
  when:
   - inventory_hostname in groups["master"]

- name: Install kubelet agent.
  dnf:
    name: "kubelet"
    state: present
    update_cache: yes
  when:
    - inventory_hostname in groups["nodes"]

- import_tasks: firewall.yml