---
- name: Copy kubernetes repository file.
  ansible.builtin.copy:
    backup: yes
    dest: "{{ kubernetes['repo_path'] }}"
    mode: "0644"
    owner: root
    group: root
    src: templates/kubernetes.repo

- name: Get repo file stats in path.
  stat:
    path: "{{ kubernetes['repo_path'] }}"
  register: repo

- name: Check if repo file was successfulley created.
  fail:
    msg: File not found in path.
  when: repo.stat.exists != True

- name: Install the latest version of the kubernetes cli applications.
  dnf:
    name: ["kubectl", "kubeadm", "kubelet"]
    state: present
    update_cache: yes

- import_tasks: kind.yml