---
- name: Inclue java install tasks.
  include_tasks: java.yml

- name: Import tasks if distribution family.
  import_tasks: "{{ ansible_os_family | lower }}.yml"
  notify:
    - create elasticsearch data dir

- name: Copy elasticsearch configuration file.
  template:
    src: "elasticsearch.yml.j2"
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elastic
    group: elastic
    backup: yes
  notify:
    - elasticsearch service setup
