---
- name: Create the web server directories.
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: "0755"
  loop:
    - "/var/www/{{ nginx_server_name }}"
    - "/var/log/nginx/{{ nginx_server_name }}"

- name: Touch create the log files.
  file:
    path: "{{ item }}"
    state: touch
    mode: "0644"
  loop:
    - "/var/log/nginx/{{ nginx_server_name }}/access.log"
    - "/var/log/nginx/{{ nginx_server_name }}/error.log"
