---
- name: Import elastic repository gpg key.
  rpm_key:
    key: "{{ elastic_repository_gpg_key }}"

- name: Install elastic repository.
  copy:
    src: "elastic.repo"
    dest: "/etc/yum.repos.d/elastic.repo"
    owner: "root"
    group: "root"
    mode: 0644

- name: Install kibana package.
  dnf:
    name: kibana-oss
    state: latest
    update_cache: yes
  notify:
    - create kibana data dir

- name: Copy kibana configuration file.
  template:
    src: "kibana.yml.j2"
    dest: /etc/kibana/kibana.yml
    owner: kibana
    group: kibana
    backup: yes
  notify:
    - kibana service setup
