---
- hosts: [localhost]
  tasks:
    # - set_fact:
    #     is_fedora: "{{ ansible_facts['distribution'] | lower == 'fedora' }}"
    #     is_redhat: "{{ ansible_facts['distribution'] | lower == 'redhat' }}"
    #     is_ubuntu: "{{ ansible_facts['distribution'] | lower == 'ubuntu' }}"
    #     distro_version: "{{ ansible_facts['distribution_major_version'] | lower }}"

    # - debug:
    #     msg: "Fedora {{ distro_version }}"
    #   when: is_fedora

    # - debug:
    #     msg: "Red Hat {{ distro_version }}"
    #   when: is_redhat

    # - debug:
    #     msg: "Ubuntu {{ distro_version }}"
    #   when: is_ubuntu

    - include_vars:
        file: stuff.yml
        name: stuff
    
    - set_fact:
        user_list: "{{ stuff['users'] }}"

    - debug:
        msg: "{{ item['pwd'] | password_hash('sha512') }}"
      loop: "{{ user_list }}"