---
- hosts: [rhels]
  become: yes
  vars:
    org_id: "11871702"
    act_key: "rheldev_key"
  tasks:
  - name: Save node distribution.
    set_fact:
      distribution: "{{ ansible_facts['distribution'] | lower }}"
  - assert:
      that:
        - "distribution == 'redhat'"
      quiet: yes
      fail_msg: "Node is not running RHEL."
  - name: Register node.
    redhat_subscription:
      activationkey: "{{ act_key }}"
      auto_attach: yes
      org_id: "{{ org_id }}"
      state: present
      force_register: yes

