---
- hosts: [all:!feds10]
  become: yes
  tasks:
    - name: Save node distribution.
      set_fact:
        distro: "{{ ansible_facts['distribution'] | lower }}"

    - name: Print hostname for the Fedora nodes.
      debug:
        msg: "IP: {{ hostvars[inventory_hostname]['vlan200_ip_addr'] }}"
      when: "distro == 'fedora'"
    
    # - name: Print hostname for the RHEL nodes.
    #   debug:
    #     msg: "RHEL distro; hostname: {{ inventory_hostname }}"
    #   when: "distro == 'redhat'"