---
- hosts: [rhels]
  become: yes
  tasks:
  - name: Update all packages.
    dnf:
      name: '*'
      state: latest
    notify: restart node

  handlers:
    - name: restart node
      reboot:
        reboot_timeout: 30

