---
- hosts: [fedoras]
  become: yes
  tasks:
    - name: Update all packages.
      dnf:
        name: '*'
        state: latest

    - name: Reboot machine.
      reboot:
        reboot_timeout: 90
