---
- import_tasks: repo.yml
#- import_tasks: storage.yml

- name: Install Mysql server packages.
  dnf:
    name: mysql-server
    state: latest

- name: Copy mysql configuration template file.
  template:
    src: "./templates/my.cnf.j2"
    dest: /etc/my.cnf.d/my.cnf
    backup: yes

- name: Open port 3306/TCP.
  firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled
